language: java
jdk:
  - openjdk8

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r springboot-web *
  - mkdir -p deploy
  - mv springboot-web.zip deploy/springboot-web.zip


deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: myspringboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private  # zip 파일 접근은 private
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      all_branches: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: myspringboot-build
    key: springboot-web.zip

    bundle_type: zip
    application: myspringboot-webservice
    deployment_group: myspringboot-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      all_branches: true

notifications:
  email:
    recipients:
      - sdk926@gmail.com